name: Build (ESP32S3 via Docker)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # 用官方 IDF 容器，包含完整环境；不依赖 setup-esp-idf Action
    container:
      image: ghcr.io/espressif/esp-idf:release-v5.1
      options: --user 0:0

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Show IDF version
        shell: bash
        run: |
          . /opt/esp/idf/export.sh
          idf.py --version

      - name: Build
        shell: bash
        run: |
          . /opt/esp/idf/export.sh
          idf.py set-target esp32s3
          idf.py build

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: esp32s3-firmware
          path: |
            build/bootloader/bootloader.bin
            build/partition_table/partition-table.bin
            build/*.bin
            build/*.elf
            build/flasher_args.json
