name: Build (ESP32S3 via Docker)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:release-v4.4.6   # ← 改成 4.4 稳定版
      options: --user 0:0

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build
        shell: bash
        run: |
          . /opt/esp/idf/export.sh
          idf.py set-target esp32s3
          idf.py fullclean
          idf.py build

      - uses: actions/upload-artifact@v4
        with:
          name: esp32s3-firmware
          path: |
            build/bootloader/bootloader.bin
            build/partition_table/partition-table.bin
            build/*.bin
            build/*.elf
            build/flasher_args.json
